site_name: gptables
repo_url: https://github.com/ONSdigital/gptables

nav:
  - Home: index.md
  - Getting started:
#  - How to:
    - Example usage: usage.md
  - API:
    - API functions: api.md
    - Theme: theme.md
    - Cover: cover.md
    - XlsxWriter wrappers: wrappers.md
    - GPTable: gptable.md
  - Reference:
    - Accessibility checklist: checklist.md
  - About GPTables:
    - Changelog: changelog.md
    - Contributors: contributors.md

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
          show_source: false
          show_signature: true
          show_root_heading: true

          filters:
              - "!^__" # Hide methods like __init__()
              - "!^_" # Hide non-public facing methods
