site_name: gptables
repo_url: https://github.com/ONSdigital/gptables

theme:
  name: material
  features:
    - toc.integrate
    - content.code.copy

nav:
  - Home: index.md
  - Getting started:
    - Tutorial: getting_started/tutorial.md
    - Table elements: getting_started/elements.md
  - How to:
    - Add additional formatting: how_to/additional_formatting.md
    - Add a custom theme: how_to/custom_theme.md
  - API:
    - API reference: api/api_reference.md
    - Functions:
      - produce_workbook(): api/functions/produce_workbook.md
      - write_workbook(): api/functions/write_workbook.md
    - Classes:
      - Cover: api/classes/cover.md
      - GPTable: api/classes/gptable.md
      - GPWorkbook: api/classes/gpworkbook.md
      - GPWorksheet: api/classes/gpworksheet.md
      - Theme: api/classes/theme.md
  - Reference:
    - Accessibility checklist: reference/checklist.md
    - Examples: reference/examples.md
    - Glossary: reference/glossary.md
  - About GPTables:
    - Contributing guidance: info/contributing.md
    - Changelog: info/changelog.md
    - Contributors: info/contributors.md

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: ["."]
        options:
          docstring_style: numpy
          show_source: false
          show_signature: true
          show_signature_annotations: true
          separate_signature: true
          separate_signature: false
          extra:
            show_type_annotations: true

          filters:
              - "!^__" # Hide methods like __init__()
              - "!^_" # Hide non-public facing methods

markdown_extensions:
- toc:
   toc_depth: 1-2
- admonition
- pymdownx.details
- pymdownx.superfences
- admonition
